### ISSUE TITLE
Boxzilla.on( "ready" ) cannot be asynchronously hooked?

### ISSUE THREAD

**Issue by lkraav** [ibericode/boxzilla.js#14]
Load order of the JS assets cannot be controlled in all scenarios. I'm trying to hook into `ready` event in my `document.ready()` callback, but it never fires. My script is loaded in the header, `window.Boxzilla` doesn't exist yet, so can't attach outside of `document.ready()`. Your thoughts?

**Comment by dannyvankooten** [comment]
Hi @lkraav,

The Boxzilla WordPress plugin was creating your Boxzilla boxes as soon as it was loaded into your DOM, as [waiting for DOMContentReady is considered an anti-pattern by Google](https://stackoverflow.com/questions/2024018/using-domcontentready-considered-anti-pattern-by-google#2024202).

However, in WordPress-context (where as you said, you don't always have control of load order) we see how this can be useful. We updated the plugin to wait for the document.ready event so that leaves you with plenty of time to hook your events.

We'll include that patch in next week's plugin update! If you're in a hurry then you can [get the latest development version from GitHub instead](https://github.com/ibericode/boxzilla-wp).

Hope that helps!

**Comment by lkraav** [comment]
Tyvm sir :+1:

**Comment by lkraav** [comment]
A small follow-up inquiry, if I may: why does `Boxzilla.boxes` not contain the populated array at the time of `ready` event? That doesn't sound `ready`.

```
17:36:59.814 Object { init: [4]</Boxzilla.init(), create: [4]</Boxzilla.create(), get: [4]</Boxzilla.get(), dismiss: [4]</Boxzilla.dismiss(), hide: [4]</Boxzilla.hide(), show: [4]</Boxzilla.show(), toggle: [4]</Boxzilla.toggle(), boxes: Array[0], _events: Object }1script.js:11:13
```

**Comment by dannyvankooten** [comment]
Hi @lkraav,

It's more `ready` in the sense of being initialised, and ready to create some boxes. 

Technical backstory is that the Boxzilla library has no way of knowing when it is "done" because it doesn't start with any boxes. You have to manually call the `Boxzilla.create()` method to create new boxes.

In the WordPress plugin we can see how a `done` event can be useful though. For now, I would suggest simply hooking into `window.load` or a similar event that fires after `document.ready` (since that's when your boxes are created).

May I ask what it is you're trying to accomplish? Maybe we can get to a better solution quicker that way.  :-)

**Comment by dannyvankooten** [comment]
Hi @lkraav ,

Github master branch of the Boxzilla WordPress plugin now triggers a `done` event right after all boxes have been created.

Hope that helps!

**Comment by lkraav** [comment]
Thanks for being so responsive. See https://github.com/lkraav/boxzilla-custom-classes

It'd be nice to just upstream this for the glorious benefit of all.

Also see https://wordpress.org/support/topic/custom-css-classes-to-boxes/

**Comment by dannyvankooten** [comment]
Hey @lkraav,

Not sure if you're still using the `Boxzilla.ready` hook but just a minor heads up that we're reverting this change as it's causing too many issues with other WordPress plugins which are not using event delegation for binding their events (eg CF7 for their AJAX functionality).

As it stands that basically means that the `Boxzilla.on('ready')` hook is pretty much useless, but there's no real drawback to simply performing the work on `document.ready` anyway in my opinion. Let me know in case your solution needs work now, I'd be happy to shoot in a PR for you.

**Comment by lkraav** [comment]
@dannyvankooten thanks for the heads up

cc @pawelkmpt
